README.md
glide.lock
provider.go
website/source/docs/providers/elasticsearch/index.html.markdown

Add support for custom ca certs and insecure connections when Elastic has a self-signed certificate.

Add support for custom CA cert

---

resource_elasticsearch_kibana_object.go

Fixes #5 
This will allow recreating kibana items when they are present in state but were deleted manually or new cluster was provisioned.

Fix kibana refresh error

---

README.md
provider.go

I've run into an issue where the current credential providers aren't fit for purpose in our CI environment.
Adding the proposed functionality would solve the problem for us.
The changes have been tested on my end and appears to work fine.

Add support for Shared Credentials Provider to AWS credentials chain

---

README.md
provider.go

Per https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html, request signing is only necessary if your domain access policy includes IAM users or roles.

Make AWS ES request signing optional

---

provider.go

This is to accommodate setup where nodes are not routable but still not hosted on AWS ESS.
Note : 
I previously added a var env + provider config for Healthcheck, but my tests showed that it wasn't required for our setup, so I ditched it.

Added sniffing var for non-routable nodes setup

---

go.mod
provider.go

The current auth methods for getting signing creds for AWS elasticsearch don't include getting the ec2 role creds which is the standard auth mechanism if the script is running on an AWS instance.
The main terraform-aws-provider does support this method along with the others.
This PR adds support and I can now run terraform with elasticsearch provider from my CI slave running on an EC2 instance.
This is the first time I've touched golang so please feel free to provide constructive criticism.

Add support for AWS ec2 role credentials

---

resource_elasticsearch_xpack_role_mapping.go
resource_elasticsearch_xpack_role_mapping_test.go
resource_elasticsearch_xpack_user.go
resource_elasticsearch_xpack_user_test.go

Intended to close https://github.com/phillbaker/terraform-provider-elasticsearch/issues/57
Currently a WIP.
Users and Role-Mappings can be imported successfully, and the tests pass.
With Roles, however, the tests currently fail with:
```
=== RUN   TestAccRoleResource_importBasic
--- FAIL: TestAccRoleResource_importBasic (0.13s)
testing.go:569: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=20) {
(string) (len=14) "applications.#": (string) (len=1) "1",
(string) (len=34) "applications.874600885.application": (string) (len=7) "testapp",
(string) (len=35) "applications.874600885.privileges.#": (string) (len=1) "2",
(string) (len=44) …
```

Import users and role mappings

---

README.md
es/provider.go
es/provider_test.go
go.mod
go.sum
test_aws_config

So we can supply the provider with an AWS_PROFILE setting (we use this in our automated terraform pipelines - where different roles may be required for different resources.  So, being able to supply the profile in code is beneficial).

Add aws profile authentication option

---

docs/index.md
es/provider.go

We configure AWS ElasticSearch to expose the endpoints internally on VPC, with an additional reverse proxy to expose ES and Kibana publicly via a custom domain. Terraform also connects to that external endpoint for configuring the ES domain, and Terraform authenticates via AWS IAM role, instead of using the admin username/password. So we need to use AWS URL signing, and with the current version of the provider it is only possible for URLs in `es.amazonws.com` subdomain, because the provider parses the domain name to extract AWS region.
Allow to specify AWS region explicitly and use it to configure URL signing for custom domains.

Allow to specify AWS region for URL signing explicitly

---

es/resource_elasticsearch_opendistro_role.go
es/resource_elasticsearch_opendistro_role_test.go

Tenant permissions for the role are optional, but not specifying them in the resource leads to the following API error:
```
Error: error creating role mapping: elastic: Error 400 (Bad Request): []
```
This simple change fixes the problem by not sending the empty permissions list in the JSON document.

Allow omitting tenant permissions

---

es/resource_elasticsearch_opendistro_ism_policy.go

Hey @phillbaker.
First, thanks for this really great `terraform` provider!
Currently, we are facing an issue when updating the first created Open Distro ISM Policy.
The **issue** is, that the first ISM Policy has a `seq_no = 0` and as a result the `seq_no` and `primary_term` parameters are not set to update an existing policy:
```
$ terraform plan               
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
elasticsearch_opendistro_ism_policy.test: Refreshing state... [id=test]
------------------------------------------------------------------------
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ …
```

Fix opendistro ism policy version conflict

---

CHANGELOG.md
docs/index.md
es/provider.go
es/provider_test.go

Add support for authenticating to AWS using an assume role ARN. This is
a very basic implementation with limited configuration options, but is
sufficient for simple use cases
Fixes #98 
@phillbaker I'm not sure how you'd want to approach automated testing with this (I've included a limited example), but I can confirm from manual tests that this works as expected.

Add support for AWS Assume Role

---

CHANGELOG.md
es/resource_elasticsearch_index.go
es/resource_elasticsearch_index_test.go

Hi @phillbaker.
Today, I want to fix the issue #75. The idea in this PR was already discussed in #55.
1. When creating an index, inspect the response for an ILM/ISM lifecycle policy.
2. If the ILM/ISM lifecycle policy contains the setting `rollover_alias`, set this field in the Terraform state.
3. On the next `terraform` run: If the `rollover_alias` is present then use this value to get the current `is_write_index`.
---
For example, you can use the following steps to reproduce:
1. Create the following `main.tf` file: 
```
provider "elasticsearch" {
url = "http://localhost:9200"
}
resource "elasticsearch_index_lifecycle_policy" "test" {
name = "test"
body = <<EOF
{
"policy": {
"phases": {
"hot": {
"min_age": "0ms",
"actions": {
"rollover": {
"max_size": "50gb"
}
}
}
}
}
}
EOF
}
resource …
```

Follow rollover alias when index is managed by ILM or ISM

---

CHANGELOG.md
es/resource_elasticsearch_index.go

Hi, me again.
Currently, we are facing an issue when creating indices with empty settings.
These are actually not necessary because the index template contains already the desired configuration.
But the current implementation results in an unexpected behavior. The index is created without the alias:
```
resource "elasticsearch_index" "test" {
name               = "test-000001"
number_of_shards   = ""
number_of_replicas = ""
refresh_interval   = ""
aliases = jsonencode({
"test" = {
"is_write_index" = true
}
})
}
```
```
GET /_alias/test
{
"error" : "alias [test] missing",
"status" : 404
}
```

Create index aliases and mappings even if no settings are set

---

.travis.yml
CHANGELOG.md
es/provider.go
es/resource_elasticsearch_index_template.go

Thanks for authoring this provider; I love managing ES in code with `terraform` instead of in my brain with clicks and keystrokes!
I ran into an issue when I was replacing an ES domain, where if an index template was stored in the TF state but didn't exist within ES, the `terraform plan` would error with a 404 error. This PR fixed it for me locally.
I _thought about_ adding tests, but I'm a n00b to both `go` and `travis`, so I didn't.

Handle the case where an index template that exists in the state is missing from the ES domain (e.g. has been manually deleted.)

---

es/resource_elasticsearch_composable_index_template.go
es/resource_elasticsearch_composable_index_template_test.go

The composable index_template code was attempting to type switch on
`meta` instead of the result of `getClient`. Since `meta` is not a
client, but rather a `ProviderConf` this caused the 'default' case of
the type switch to run which made the tests skip and not fail.
```
Error: index_template endpoint only available from ElasticSearch >= 7.8, got version < 7.0.0 (*es.ProviderConf)
```
```
$ TF_ACC=1 go test ./... -v -run TestAccElasticsearchComposableIndexTemplate
?   	github.com/phillbaker/terraform-provider-elasticsearch	[no test files]
=== RUN   TestAccElasticsearchComposableIndexTemplate
TestAccElasticsearchComposableIndexTemplate: resource_elasticsearch_composable_index_template_test.go:34: /_index_template endpoint only supported on ES >= 7.8
--- SKIP: …
```

Fix composable_index_template + tests

---

docs/resources/snapshot_repository.md

The setting argument needs to be assigned to, not referenced as a block.

Small fix for elasticsearch_snapshot_repository docs

---

CHANGELOG.md
docs/resources/opendistro_role.md
es/resource_elasticsearch_opendistro_role.go
es/resource_elasticsearch_opendistro_role_test.go
es/util.go

In the same way as Field Level Security, I propose to add support for Document Level Security in Opendistro Role.
See documentation here https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/document-level-security/

Add Document Level Security support for Opendistro role

---

es/resource_elasticsearch_opendistro_user.go
es/resource_elasticsearch_xpack_user.go
es/util.go

Hash the password and save it to state. Changing the password in terraform will cause the password to update. 
```
john.delivuk@JohnDelivuk-MBP elasticsearch-provider % terraform apply
2021/01/15 20:12:53 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's internal logs.
----
2021/01/15 20:12:53 [INFO] Terraform version: 0.13.5  
2021/01/15 20:12:53 [INFO] Go runtime version: go1.14.12
2021/01/15 20:12:53 [INFO] CLI args: []string{"/usr/local/bin/terraform", "apply"}
2021/01/15 20:12:53 [INFO] CLI command args: []string{"apply"}
2021/01/15 20:12:53 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's …
```

Hash password for tf managed users

---

es/resource_elasticsearch_opendistro_destination.go
es/util.go

~The normalizeDestination function already exists but isn't being used in the function to GET destinations. This adds that step, as well as~. I'm an idiot. The normalizeDestination gets called via the diffsuppress.
Adds "id" to the list of keys to ignore. The "id" is a nested v alue that gets created with the lastest versions of ES.

Add "id" to normalizeDestination to account for nested "id" key in newer versions of ES

---

es/util.go

Observed that after creating an `elasticsearch_opendistro_monitor` resource, diffs are perpetually caused by the monitor's `id` and its action/trigger `id` values, which are added after creation by the API.  These will always change between applies, as this diff causes them to be re-created.
This PR suppresses the diff on subsequent applies by normalizing out those IDs.
<details>
<summary>
Demonstration of the issue:
</summary>
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "elasticsearch_opendistro_monitor" "test_alert" {
~ body = jsonencode(
~ {
+ schema_version = 3
~ triggers       = [
~ {
~ actions   = [
~ {
- id               = …
```

Normalize IDs in resource_elasticsearch_opendistro_monitor

---

es/util.go

This PR adds `schema_version` and `ism_template.last_updated_time` to ignored props in policy normalization.

fix: added schema_version and nested last_updated_time for ism compliance

---

docs/index.md
es/provider.go

This changes the default value of the provider `token` field to read
from the environment variable `ELASTICSEARCH_TOKEN`.
fixes #179

Support configuring provider token from environment

---

docs/resources/xpack_index_lifecycle_policy.md

Just a small fix for the ILM policy link to the API docs in es-xpack.

[doc] Index Lifecycle Management fix link to xpack doc

---

es/resource_elasticsearch_index.go

This PR resolves https://github.com/phillbaker/terraform-provider-elasticsearch/issues/194. Index settings with a `.` in their name were only set at creation time, and never at update time due to a missed `strings.Replace(key, ".", "_", -1)`.
I've tested this locally using the same setup described in the issue, and get the expected behaviour where an update to the index block in terraform is respected by the cluster.
I'm not sure if there's a changelog or anything else I should update here - let me know @phillbaker, and thanks for all your work on this module 😄

Fix updates on index settings with '.' in name

---

es/provider.go

Profiles are defined in the shared config file so it makes sense to load that too.
Or should this be on line 461 as part of the initialisation of the `sessOpts`?
Follow up to 72475b5
My usecase: Only providing the profile name without needing the environment variable `AWS_SDK_LOAD_CONFIG=1`

[aws] Also load shared config for a profile

---

es/provider.go

This PR resolves https://github.com/phillbaker/terraform-provider-elasticsearch/issues/177. The setup is a cluster running in an AWS VPC, which i am connecting to via an SSH tunnel on `localhost:9999`. I recieved the following error regardless of what the `insecure` option was set to:
```
Error: Get "https://localhost:9999/terraform-test/_settings?flat_settings=true": x509: certificate is valid for *.us-east-1.es.amazonaws.com, not localhost
```
This is because `insecure` is used to set the TLS options on the client created in `awsSession()`, but that client is not passed through to `aws_signing_client.New()`, resulting in `http.DefaultClient` being used instead. By passing the client through, certificate validation is skipped as expected.

Pass conf.insecure correctly in awsHttpClient()

---

docs/index.md
es/http.go
es/provider.go

This PR adds a new provider configuration option `host_override`. The option enables the use of `sign_aws_requests = true` when accessing Elasticsearch via an SSH tunnel, as well as removing the need to set `insecure = true`.
I've also added a note to the documentation detailing when this parameter should be used. Happy to change the naming if there's terms you think would work better too!
Consider the following example - an SSH tunnel is setup on `localhost:9999`, pointing to an AWS VPC cluster `vpc-<******>.us-east-1.es.amazonaws.com`. Without using `insecure = true`, the connection will error with the following:
> Error: health check timeout: Head "https://localhost:9999": x509: certificate is valid for *.us-east-1.es.amazonaws.com, not localhost: no Elasticsearch node available
While …

Add host_override parameter to allow connections via SSH tunnel with `sign_aws_requests = true`

---

es/resource_elasticsearch_component_template.go
es/resource_elasticsearch_composable_index_template.go
es/resource_elasticsearch_kibana_alert.go
es/util.go

Hi, It's me again.
Currently, we are facing an issue when creating index templates in an AWS OpenSearch cluster (compatibility mode disabled).
According to the [docs](https://opensearch.org/faq/#q1.1), OpenSearch is basically a fork of  Elasticsearch/Kibana v7.10.2. 
As a result we set the `elasticsearch_version` in the provider configuration.
At this point everything is working as expected excepts of creating `elasticsearch_composable_index_template` resources.
```
provider "elasticsearch" {
url                   = "https://..."
aws_region            = "eu-central-1"
elasticsearch_version = "7.10.2"
}
resource "elasticsearch_composable_index_template" "template_1" {
name = "template_1"
body = "{ ... }"
}
```
```
elasticsearch_composable_index_template.template_1: Creating...
╷
│ Error: …
```

Use esVersion from ProviderConf to compare versions

---

docs/resources/xpack_watch.md

Uplift "name" attribute within docs to "watch_id".
Existing functionality already uses watch_id, doc updates may have just been missed when this was applied!

Resolve incorrect attribute "name" in docs for elasticsearch_xpack_watch

---

docs/index.md
es/provider.go

```hcl
provider "elasticsearch" {
aws_region            = data.aws_region.current.name
aws_signature_service = "execute-api"
healthcheck           = false
url                   = "https://your-iam-secured-api-gateway"
}
```
fixes #248

feat: configurable service key in AWS signatures

---

README.md
docs/guides/rollover.md
docs/resources/opendistro_ism_policy.md
docs/resources/opendistro_kibana_tenant.md
docs/resources/opendistro_monitor.md
docs/resources/opendistro_role.md
docs/resources/opendistro_roles_mapping.md
docs/resources/opendistro_user.md
examples/README.md

Added a language to every code blocks that haven't been specified.
I noticed that some code blocks on the documents have been broken due to the lack of language settings. I added them to all the code blocks that doesn't have language settings for syntax highlighting.
----
I noticed that this repository is using variety of syntax languages for .tf files, [terraform](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b3995de14289dfb9a754f1c18c0c8881fa4ad742/docs/resources/xpack_snapshot_lifecycle_policy.md?plain=1#L14), [tf](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/eeff3b65d396ea460eb1f6a11f26c9aa5dc4e187/docs/index.md?plain=1#L19), and [hcl](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/2cbf4b515cd1a845ad6936c6d13031482bfd55c …

Documentation: Specify languages for syntax highlighting

---

es/resource_elasticsearch_xpack_role.go

When Kibana xpack roles are renamed they should be recreated. The current behaviour leads to two roles being present, one with the old name and one with the new name. This causes issues with role mappings and noise in TF plans.

xpack role rename should force recreation

---

docs/resources/opensearch_user.md

Using example from https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/opensearch_user:
```
resource "elasticsearch_opensearch_user" "mapper" {
username    = "app-reader"
password    = "supersekret123!"
description = "a reader role for our app"
}
```
... fails on AWS ES domain with non-descriptive error:
```
Error: elastic: Error 400 (Bad Request)
```
To debug I changed the provider URL to a netcat listener to catch the request. On replay on ES domain I got this error:
```
{
"status": "error",
"reason": "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character."
}
```
The password in the example does not have upper case characters, so I suggest a documentation fix.
I …

improve elasticsearch_opensearch_user example password + description

---

es/resource_elasticsearch_index.go

Noticed this incomplete error message when destroying an index.

Minor resource_elasticsearch_index error message fix
